language: python
matrix:
    include:
    - python: "2.7"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc-py2"
    - python: "3.4"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc-py34"
    - python: "3.5"
      env:
          - AIO_AVAILABLE=false
          - COVERAGERC=".coveragerc"
    - python: "3.6"
      env:
          - AIO_AVAILABLE=true
          - COVERAGERC=".coveragerc"
    - python: "3.7"
      dist: xenial
      sudo: required
      env:
          - AIO_AVAILABLE=true
          - COVERAGERC=".coveragerc"
install:
  - pip install -U pip setuptools wheel
  - pip install -U pytest pytest-cov coveralls
  - sh -c "if [ '$AIO_AVAILABLE' = 'true' ]; then pip install -U pytest-asyncio; fi"
  - pip install -e .
script:
  - py.test --cov-config $COVERAGERC --cov=pydispatch
after_success:
  - coveralls --rcfile="$COVERAGERC"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: "3.6"
    tags: true
  user: nocarryr
  password:
    secure: C6UEEhM/LqhGhEN/p33j2aLDeQlcQvXiEMWH+nnz5RQOEBiFT9vskWiZmOpLq63vWQQAknjloo9WQ4e1pvVTvkzlWyKZ+Anipu8aC/tSAyKQ3snPtAgjH8SVBBZMlU4ks9GQo0+uBuD77Ux9Gkp3+uEjkAVb1FrUGkhdTGmZoz96nvWpnnS+YeqxlNx6N2lFuFetsW9kbTP6WSDOph2AasFW1X91Lm5TSxeNpy2tpz+eLFgkbBrw5u0790OIVnxWy7L5DgsejKfhAZgyPRCHcbKwygo8KvssrmsSVLT62yQlqehRmN2ui1bH0YPqib4Saz78saFcslLLnjjf9Pk5sXcFtn61y2B1l+gT9bQZCoDVLiP8ru335CmoJqvbzJooF/7EbzCaC2m9vr0LbKXsqcgc0+j3fYTx8IZoYK1KplPFD4nhMXNnWBHfvxsiww4sqQu7DvGFFydlMgNpZcrbCk/hBzVYeZPKsGNUVkvpPAhjtJ4ULJiFmcKBbJ4CzUEYuOw3HAI+FGpJMvvU/l7Rg9Xv/TbTdjHPX+DWkF9jdXMClTMu0Iki6Xi4Ap2KoOsOzMmP69AhzCTzSrW9ANjb/YboFAdJZVDW9VMHYp0CGIavdKhWf8kGDOcZy6kf6CMR7HKJmn4PMvwRSaRaKoSkBzxJqELg7d+evHVM8WgB8S0=
